AspMvcDemoProject/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspMvcDemoProject.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult CVM()
        {
            return View();
        }

        public IActionResult Index()
        {
            //return "Hello World!!!";
            return View();
        }

        public IActionResult MyAction(int id)
        {
            return Ok($"Has been done successfully with id = {id}"); // 200
        }

        public IActionResult StatusCode()
        {
            // return BadRequest(); // 400 
            // return Unauthorized("Message"); // 401
            // return NotFound(); // 404
            return new UnsupportedMediaTypeResult();
        }

        public IActionResult RedirectResult()
        {
            return Redirect("https://google.com");
        }

        public IActionResult JsonResult()
        {
            return Json(new
            {
                message = "this is a Json result",
                date = DateTime.Now
            });
        }

        public IActionResult ContentResult()
        {
            return Content("Hello! Is a content!");
        }
    }
}

AspMvcDemoProject/Controllers/OrderController.cs
using AspMvcDemoProject.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using AspMvcDemoProject.ViewModels;
using AspMvcDemoProject.Models;
using System.Threading.Tasks;

namespace AspMvcDemoProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDbContext _context;

        public OrderController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var orders = _context.Orders.ToList();

            return View(orders);
        }

        public IActionResult GetProdutsWithOrderId(int? id)
        {
            var orderProducts = _context.OrderProducs;
            var products = _context.Products
                .Select(p => new ProductVM
                {
                    Id = p.P_Code,
                    Descript = p.P_descript,
                    Price = p.P_Price,
                    IsActive = orderProducts
                        .Where(op => op.P_Code == p.P_Code && op.OrderId == id)
                        .FirstOrDefault() == null 
                                ? false : true
                });

            SaveProductsVM spvm = new SaveProductsVM
            {
                Products = products.ToList(),
                OrderId = id ?? -1
            };

            return PartialView(spvm);
        }

        public IActionResult SaveProducts(SaveProductsVM obj)
        {
            var remove = _context.OrderProducs
                .Where(op => op.OrderId == obj.OrderId);

            _context.RemoveRange(remove);

            var add = obj.Products
                .Where(p => p.IsActive)
                .Select(op => new OrderProducs
                {
                    OrderId = obj.OrderId,
                    P_Code = op.Id
                });

            _context.AddRange(add);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

AspMvcDemoProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using AspMvcDemoProject.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspMvcDemoProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AspMvcDemoProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var list = _context.Products.Include(p => p.Vendor);

            return View(list);
        }

        public IActionResult GetProdutsByVendorCode(int? id)
        {
            var products = _context.Products
                .Where(p => p.V_code == id)
                .Select(e => e.P_descript);

            if (products.Count() == 0)
            {
                return Content("No Products found");
            }

            return Content(string.Join("<br>", products));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Vendors = 
                new SelectList(_context.Vendors, "V_code", "V_name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product obj)
        {
            if (ModelState.IsValid)
            {
                _context.Products.Add(obj);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.Vendors =
                new SelectList(_context.Vendors, "V_code", "V_name");
            return View(obj);
        }
    }
}

AspMvcDemoProject/Controllers/VendorController.cs
using AspMvcDemoProject.Data;
using AspMvcDemoProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspMvcDemoProject.Controllers
{
    public class VendorController : Controller
    {
        private readonly AppDbContext _context;
        private readonly Mapper _mapper = new Mapper();

        public VendorController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            // var list = _context.Vendors;
            var list = MockingRepository.GetVendors();
            return View(list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(VendorDto obj)
        {
            Vendor newVendor = _mapper.Map(obj);
            MockingRepository.AddVendor(newVendor);

            return RedirectToAction("Index");
        }
    }
}

AspMvcDemoProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspMvcDemoProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspMvcDemoProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="Index">Vendors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="CVM">Buy candy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor2" asp-action="Index">Vendors from template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AspMvcDemoProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>